// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: api/ocp-task-api/ocp-task-api.proto

package oct_task_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskDificulty int32

const (
	TaskDificulty_Beginner TaskDificulty = 0
	TaskDificulty_Easy     TaskDificulty = 1
	TaskDificulty_Normal   TaskDificulty = 2
	TaskDificulty_Hard     TaskDificulty = 3
)

// Enum value maps for TaskDificulty.
var (
	TaskDificulty_name = map[int32]string{
		0: "Beginner",
		1: "Easy",
		2: "Normal",
		3: "Hard",
	}
	TaskDificulty_value = map[string]int32{
		"Beginner": 0,
		"Easy":     1,
		"Normal":   2,
		"Hard":     3,
	}
)

func (x TaskDificulty) Enum() *TaskDificulty {
	p := new(TaskDificulty)
	*p = x
	return p
}

func (x TaskDificulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskDificulty) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ocp_task_api_ocp_task_api_proto_enumTypes[0].Descriptor()
}

func (TaskDificulty) Type() protoreflect.EnumType {
	return &file_api_ocp_task_api_ocp_task_api_proto_enumTypes[0]
}

func (x TaskDificulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskDificulty.Descriptor instead.
func (TaskDificulty) EnumDescriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{0}
}

type DescribeTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *DescribeTaskRequest) Reset() {
	*x = DescribeTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskRequest) ProtoMessage() {}

func (x *DescribeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskRequest.ProtoReflect.Descriptor instead.
func (*DescribeTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeTaskRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DescribeTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *DescribeTaskResponse) Reset() {
	*x = DescribeTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskResponse) ProtoMessage() {}

func (x *DescribeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskResponse.ProtoReflect.Descriptor instead.
func (*DescribeTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Описание задачи
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId      uint64        `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Dificulty   TaskDificulty `protobuf:"varint,3,opt,name=dificulty,proto3,enum=ocp.task.api.TaskDificulty" json:"dificulty,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetDificulty() TaskDificulty {
	if x != nil {
		return x.Dificulty
	}
	return TaskDificulty_Beginner
}

var File_api_ocp_task_api_ocp_task_api_proto protoreflect.FileDescriptor

var file_api_ocp_task_api_ocp_task_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e,
	0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x3e, 0x0a,
	0x14, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x7c, 0x0a,
	0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x52, 0x09, 0x64, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x2a, 0x3d, 0x0a, 0x0d, 0x54,
	0x61, 0x73, 0x6b, 0x44, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x0c, 0x0a, 0x08,
	0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x61,
	0x73, 0x79, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x61, 0x72, 0x64, 0x10, 0x03, 0x32, 0x7d, 0x0a, 0x0a, 0x4f, 0x63,
	0x70, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x70, 0x69, 0x12, 0x6f, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x21, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f,
	0x7b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x68,
	0x74, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f,
	0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x63, 0x74,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_ocp_task_api_ocp_task_api_proto_rawDescOnce sync.Once
	file_api_ocp_task_api_ocp_task_api_proto_rawDescData = file_api_ocp_task_api_ocp_task_api_proto_rawDesc
)

func file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP() []byte {
	file_api_ocp_task_api_ocp_task_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_task_api_ocp_task_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_task_api_ocp_task_api_proto_rawDescData)
	})
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescData
}

var file_api_ocp_task_api_ocp_task_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ocp_task_api_ocp_task_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_ocp_task_api_ocp_task_api_proto_goTypes = []interface{}{
	(TaskDificulty)(0),           // 0: ocp.task.api.TaskDificulty
	(*DescribeTaskRequest)(nil),  // 1: ocp.task.api.DescribeTaskRequest
	(*DescribeTaskResponse)(nil), // 2: ocp.task.api.DescribeTaskResponse
	(*Task)(nil),                 // 3: ocp.task.api.Task
}
var file_api_ocp_task_api_ocp_task_api_proto_depIdxs = []int32{
	3, // 0: ocp.task.api.DescribeTaskResponse.task:type_name -> ocp.task.api.Task
	0, // 1: ocp.task.api.Task.dificulty:type_name -> ocp.task.api.TaskDificulty
	1, // 2: ocp.task.api.OcpTaskApi.DescribeTask:input_type -> ocp.task.api.DescribeTaskRequest
	2, // 3: ocp.task.api.OcpTaskApi.DescribeTask:output_type -> ocp.task.api.DescribeTaskResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ocp_task_api_ocp_task_api_proto_init() }
func file_api_ocp_task_api_ocp_task_api_proto_init() {
	if File_api_ocp_task_api_ocp_task_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_task_api_ocp_task_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_task_api_ocp_task_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_task_api_ocp_task_api_proto_depIdxs,
		EnumInfos:         file_api_ocp_task_api_ocp_task_api_proto_enumTypes,
		MessageInfos:      file_api_ocp_task_api_ocp_task_api_proto_msgTypes,
	}.Build()
	File_api_ocp_task_api_ocp_task_api_proto = out.File
	file_api_ocp_task_api_ocp_task_api_proto_rawDesc = nil
	file_api_ocp_task_api_ocp_task_api_proto_goTypes = nil
	file_api_ocp_task_api_ocp_task_api_proto_depIdxs = nil
}
