// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: api/ocp-task-api/ocp-task-api.proto

package oct_task_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskDificulty int32

const (
	TaskDificulty_Beginner TaskDificulty = 0
	TaskDificulty_Easy     TaskDificulty = 1
	TaskDificulty_Normal   TaskDificulty = 2
	TaskDificulty_Hard     TaskDificulty = 3
)

// Enum value maps for TaskDificulty.
var (
	TaskDificulty_name = map[int32]string{
		0: "Beginner",
		1: "Easy",
		2: "Normal",
		3: "Hard",
	}
	TaskDificulty_value = map[string]int32{
		"Beginner": 0,
		"Easy":     1,
		"Normal":   2,
		"Hard":     3,
	}
)

func (x TaskDificulty) Enum() *TaskDificulty {
	p := new(TaskDificulty)
	*p = x
	return p
}

func (x TaskDificulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskDificulty) Descriptor() protoreflect.EnumDescriptor {
	return file_api_ocp_task_api_ocp_task_api_proto_enumTypes[0].Descriptor()
}

func (TaskDificulty) Type() protoreflect.EnumType {
	return &file_api_ocp_task_api_ocp_task_api_proto_enumTypes[0]
}

func (x TaskDificulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskDificulty.Descriptor instead.
func (TaskDificulty) EnumDescriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{0}
}

type ListTasksV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListTasksV1Request) Reset() {
	*x = ListTasksV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTasksV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksV1Request) ProtoMessage() {}

func (x *ListTasksV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksV1Request.ProtoReflect.Descriptor instead.
func (*ListTasksV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListTasksV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *ListTasksV1Response) Reset() {
	*x = ListTasksV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTasksV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksV1Response) ProtoMessage() {}

func (x *ListTasksV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksV1Response.ProtoReflect.Descriptor instead.
func (*ListTasksV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksV1Response) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTaskV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Dificulty   TaskDificulty `protobuf:"varint,3,opt,name=dificulty,proto3,enum=ocp.task.api.TaskDificulty" json:"dificulty,omitempty"`
}

func (x *CreateTaskV1Request) Reset() {
	*x = CreateTaskV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskV1Request) ProtoMessage() {}

func (x *CreateTaskV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskV1Request.ProtoReflect.Descriptor instead.
func (*CreateTaskV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskV1Request) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskV1Request) GetDificulty() TaskDificulty {
	if x != nil {
		return x.Dificulty
	}
	return TaskDificulty_Beginner
}

type CreateTaskV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *CreateTaskV1Response) Reset() {
	*x = CreateTaskV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskV1Response) ProtoMessage() {}

func (x *CreateTaskV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskV1Response.ProtoReflect.Descriptor instead.
func (*CreateTaskV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskV1Response) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type RemoveTaskV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *RemoveTaskV1Request) Reset() {
	*x = RemoveTaskV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTaskV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskV1Request) ProtoMessage() {}

func (x *RemoveTaskV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskV1Request.ProtoReflect.Descriptor instead.
func (*RemoveTaskV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveTaskV1Request) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type RemoveTaskV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *RemoveTaskV1Response) Reset() {
	*x = RemoveTaskV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTaskV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskV1Response) ProtoMessage() {}

func (x *RemoveTaskV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskV1Response.ProtoReflect.Descriptor instead.
func (*RemoveTaskV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveTaskV1Response) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DescribeTaskV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *DescribeTaskV1Request) Reset() {
	*x = DescribeTaskV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeTaskV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskV1Request) ProtoMessage() {}

func (x *DescribeTaskV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskV1Request.ProtoReflect.Descriptor instead.
func (*DescribeTaskV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeTaskV1Request) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type DescribeTaskV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *DescribeTaskV1Response) Reset() {
	*x = DescribeTaskV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeTaskV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTaskV1Response) ProtoMessage() {}

func (x *DescribeTaskV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTaskV1Response.ProtoReflect.Descriptor instead.
func (*DescribeTaskV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeTaskV1Response) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Описание задачи
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId      uint64        `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Dificulty   TaskDificulty `protobuf:"varint,3,opt,name=dificulty,proto3,enum=ocp.task.api.TaskDificulty" json:"dificulty,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_task_api_ocp_task_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetDificulty() TaskDificulty {
	if x != nil {
		return x.Dificulty
	}
	return TaskDificulty_Beginner
}

var File_api_ocp_task_api_ocp_task_api_proto protoreflect.FileDescriptor

var file_api_ocp_task_api_ocp_task_api_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e,
	0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x3f, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x72, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x52, 0x09, 0x64, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x22, 0x2f, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x37,
	0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x39, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x22, 0x40, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x22, 0x7c, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x69, 0x66, 0x69,
	0x63, 0x75, 0x6c, 0x74, 0x79, 0x52, 0x09, 0x64, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x2a, 0x3d, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x69, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74,
	0x79, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x45, 0x61, 0x73, 0x79, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x61, 0x72, 0x64, 0x10, 0x03, 0x32,
	0xcb, 0x03, 0x0a, 0x0a, 0x4f, 0x63, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x70, 0x69, 0x12, 0x65,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x56, 0x31, 0x12, 0x20, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x78, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61,
	0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x7b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x7d, 0x12,
	0x68, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x12,
	0x21, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x09,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x72, 0x0a, 0x0c, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x12, 0x21, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x2a, 0x13, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x2f, 0x7b, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x3e, 0x5a,
	0x3c, 0x67, 0x69, 0x68, 0x74, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e,
	0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x61, 0x70, 0x69,
	0x3b, 0x6f, 0x63, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_task_api_ocp_task_api_proto_rawDescOnce sync.Once
	file_api_ocp_task_api_ocp_task_api_proto_rawDescData = file_api_ocp_task_api_ocp_task_api_proto_rawDesc
)

func file_api_ocp_task_api_ocp_task_api_proto_rawDescGZIP() []byte {
	file_api_ocp_task_api_ocp_task_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_task_api_ocp_task_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_task_api_ocp_task_api_proto_rawDescData)
	})
	return file_api_ocp_task_api_ocp_task_api_proto_rawDescData
}

var file_api_ocp_task_api_ocp_task_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_ocp_task_api_ocp_task_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ocp_task_api_ocp_task_api_proto_goTypes = []interface{}{
	(TaskDificulty)(0),             // 0: ocp.task.api.TaskDificulty
	(*ListTasksV1Request)(nil),     // 1: ocp.task.api.ListTasksV1Request
	(*ListTasksV1Response)(nil),    // 2: ocp.task.api.ListTasksV1Response
	(*CreateTaskV1Request)(nil),    // 3: ocp.task.api.CreateTaskV1Request
	(*CreateTaskV1Response)(nil),   // 4: ocp.task.api.CreateTaskV1Response
	(*RemoveTaskV1Request)(nil),    // 5: ocp.task.api.RemoveTaskV1Request
	(*RemoveTaskV1Response)(nil),   // 6: ocp.task.api.RemoveTaskV1Response
	(*DescribeTaskV1Request)(nil),  // 7: ocp.task.api.DescribeTaskV1Request
	(*DescribeTaskV1Response)(nil), // 8: ocp.task.api.DescribeTaskV1Response
	(*Task)(nil),                   // 9: ocp.task.api.Task
}
var file_api_ocp_task_api_ocp_task_api_proto_depIdxs = []int32{
	9, // 0: ocp.task.api.ListTasksV1Response.tasks:type_name -> ocp.task.api.Task
	0, // 1: ocp.task.api.CreateTaskV1Request.dificulty:type_name -> ocp.task.api.TaskDificulty
	9, // 2: ocp.task.api.DescribeTaskV1Response.task:type_name -> ocp.task.api.Task
	0, // 3: ocp.task.api.Task.dificulty:type_name -> ocp.task.api.TaskDificulty
	1, // 4: ocp.task.api.OcpTaskApi.ListTasksV1:input_type -> ocp.task.api.ListTasksV1Request
	7, // 5: ocp.task.api.OcpTaskApi.DescribeTaskV1:input_type -> ocp.task.api.DescribeTaskV1Request
	3, // 6: ocp.task.api.OcpTaskApi.CreateTaskV1:input_type -> ocp.task.api.CreateTaskV1Request
	5, // 7: ocp.task.api.OcpTaskApi.RemoveTaskV1:input_type -> ocp.task.api.RemoveTaskV1Request
	2, // 8: ocp.task.api.OcpTaskApi.ListTasksV1:output_type -> ocp.task.api.ListTasksV1Response
	8, // 9: ocp.task.api.OcpTaskApi.DescribeTaskV1:output_type -> ocp.task.api.DescribeTaskV1Response
	4, // 10: ocp.task.api.OcpTaskApi.CreateTaskV1:output_type -> ocp.task.api.CreateTaskV1Response
	6, // 11: ocp.task.api.OcpTaskApi.RemoveTaskV1:output_type -> ocp.task.api.RemoveTaskV1Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_ocp_task_api_ocp_task_api_proto_init() }
func file_api_ocp_task_api_ocp_task_api_proto_init() {
	if File_api_ocp_task_api_ocp_task_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTasksV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTasksV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTaskV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTaskV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeTaskV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeTaskV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_task_api_ocp_task_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_task_api_ocp_task_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_task_api_ocp_task_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_task_api_ocp_task_api_proto_depIdxs,
		EnumInfos:         file_api_ocp_task_api_ocp_task_api_proto_enumTypes,
		MessageInfos:      file_api_ocp_task_api_ocp_task_api_proto_msgTypes,
	}.Build()
	File_api_ocp_task_api_ocp_task_api_proto = out.File
	file_api_ocp_task_api_ocp_task_api_proto_rawDesc = nil
	file_api_ocp_task_api_ocp_task_api_proto_goTypes = nil
	file_api_ocp_task_api_ocp_task_api_proto_depIdxs = nil
}
